name: Exercises Feedback
description: Runs model to verify whether an exercise is correct or not

on:
  workflow_call:
    inputs:
      listdir:
        required: true
        default: 'nothing'
        type: string

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Python Marker
      shell: bash
      run: |
        echo ${{ inputs.listdir }}
        python $GITHUB_ACTION_PATH/python/marker1.py 

    - name: Review File
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/scripts/check_file.sh
  
    - name: Check for Secret
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/scripts/check_secrets.sh