name: Exercises Feedback
description: Runs model to verify whether an exercise is correct or not

jobs:
  Review Exercise 1:
    runs-on: ubuntu-latest
    steps:
        - name: Arrange
          run: $GITHUB_ACTION_PATH/scripts/arrange.sh

        - name: Act
          run: $GITHUB_ACTION_PATH/scripts/act.sh

        - name: Assert
          run: |
            $GITHUB_ACTION_PATH/scripts/assert.sh > output.txt
            echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
            cat output.txt >> $GITHUB_STEP_SUMMARY

        - name: Clean up
          run: |
            cat output.txt
            $GITHUB_ACTION_PATH/scripts/cleanup.sh
